Calculation script now recognizes if file or directory does not exist

diff --git a/scripts/caansatofi b/scripts/caansatofi
--- a/scripts/caansatofi
+++ b/scripts/caansatofi
@@ -1,7 +1,13 @@
 # Calculate And Save To File
 # $1 defines input directory
 # $2 defines output file
+if [ ! -d $1 ] || [ ! -f $1 ]; then
+	echo "File / directory not found"
+	exit 1
+fi
+
 WORKINGDIR=$(pwd)
 echo "Ran on $(date) with parameter $1" >> "$WORKINGDIR/$2"
 cd $1
 find -type f -exec md5sum {} + >> "$WORKINGDIR/$2"
+exit 0
